# Default colors
[colors.primary]
background = '#100F0F'
foreground = '#CECDC3'
dim_foreground = '#F2F0E5'
bright_foreground = '#E6E4D9'

# Cursor colors
[colors.cursor]
text = '#100F0F'
cursor = '#CECDC3'

# Normal colors
[colors.normal]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#CECDC3'

# Bright colors
[colors.bright]
black = '#575653'
red = '#D14D41'
green = '#879A39'
yellow = '#D0A215'
blue = '#4385BE'
magenta = '#CE5D97'
cyan = '#3AA99F'
white = '#FFFCF0'

# Dim colors
[colors.dim]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#CECDC3'
