theme = "base16_terminal" # 设置主题

[editor]
line-number = "relative" # 相对行号
# 高亮显示
cursorline = true # 高亮显示行
cursorcolumn = true # 高亮显示列
default-line-ending = "native"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.soft-wrap]
enable = true
max-wrap = 25 # 增加该值可以降低强制从一个词中间软换行
max-indent-retain = 0
# wrap-indicator = ""  # 设置后可以不现实软换行符号
wrap-at-text-width = false

