#markdown

[[language]]
name = "markdown"
language-servers = [ "marksman", "zk", "mdpls", "ltex-ls" ]

[language-server.zk]
command = "zk"

[language-server.mdpls]
command = "mdpls"
config = { markdown.preview.auto = false, markdown.preview.browser = "firefox" }

[language-server.ltex-ls.config.ltex.dictionary]
"zh-CN" = ["Tp-Note","Zettelkasten"]

#matlab

[language-server.matlab-ls]
command = "matlab-language-server"
args = ["--stdio"]

[language-server.matlab-ls.config.MATLAB]
indexWorkspace = false
#installPath = "/PATH/TO/MATLAB/INSTALLATION"
matlabConnectionTiming = "onStart"
telemetry = false

[[language]]
name = "matlab"
scope = "source.m"
file-types = ["m"]
language-servers = ["matlab-ls"]
comment-token = "%"
shebangs = ["octave-cli", "matlab"]
indent = { tab-width = 2, unit = "  " }

#python
[[language]]
name = "python"
[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m",  "debugpy.adapter"]
[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }
