# Markdown

[[language]]
name = "markdown"
soft-wrap.enable = true
text-width = 80
soft-wrap.wrap-at-text-width = true
language-servers = [ "marksman", "ltex-ls-plus" ]

[language-server.ltex-ls-plus.config]
ltex.dictionary = { "zh-CN" = ["Tp-Note", "Zettelkasten"] }
ltex.language = "zh-CN"

[language-server.iwe]
command = "iwes"

# Typst

[[language]]
name = "typst"
text-width = 80
soft-wrap.wrap-at-text-width = true
soft-wrap.enable = true
language-servers = [ "tinymist", "ltex-ls" ]

# MatLab

[language-server.matlab-ls]
command = "matlab-language-server"
args = ["--stdio"]

[language-server.matlab-ls.config.MATLAB]
indexWorkspace = false
#installPath = "/PATH/TO/MATLAB/INSTALLATION"
matlabConnectionTiming = "onStart"
telemetry = false

[[language]]
name = "matlab"
scope = "source.m"
file-types = ["m"]
language-servers = ["matlab-ls"]
comment-token = "%"
shebangs = ["octave-cli", "matlab"]
indent = { tab-width = 2, unit = "  " }

# Python
[[language]]
name = "python"
[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m",  "debugpy.adapter"]
[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

# Hyprlang
[[language]]
name = "hyprlang"
language-servers = [ "hyprls" ]
[language-server.hyprls]
command = "hyprls"
